In [1]:
import numpy as np
import random
import math
import matplotlib.pyplot as plt
import copy

### Imp Note:
- The algorithm works fine in all cases except those where the solution is not unique.

In [2]:
# INPUTS
# Case 1
n = 3
w = np.array([[2, 16, 14],
              [13, 11, 2],
              [15, 4, 13]]) 

# # Case 2
# n = 3
# w = np.array([[2, 6, 4],
#               [3, 1, 2],
#               [5, 4, 3]]) 

# # Case 3
# n = 4 
# w = np.array([[82, 83, 69, 92],
#               [77, 37, 49, 92],
#               [11, 69, 5, 86],
#               [8, 9, 98, 23]])

iter_no = 100

In [3]:
w *= -1 # to find max
w_T = w.T

M_ab = np.zeros((n,n)) # i,j
M_ab_new = np.zeros((n,n)) # i,j

M_ba = np.zeros((n,n)) # j,i
M_ba_new = np.zeros((n,n)) # j,i

P = np.arange(n)
print(M_ab.shape)
print(M_ba.shape)

(3, 3)
(3, 3)


In [4]:
for i in range(n):
    for j in range(n):
        M_ab[i][j] = w[i][j]
        M_ba[j][i] = w[i][j] 

print(M_ab)
print(M_ba)

[[ -2. -16. -14.]
 [-13. -11.  -2.]
 [-15.  -4. -13.]]
[[ -2. -13. -15.]
 [-16. -11.  -4.]
 [-14.  -2. -13.]]


In [5]:
def calc_max(M_ba, i, j, n):
    ma = -math.inf
    for k in range(n):
        if(k != j):
            if(M_ba[k][i] > ma):
                ma = M_ba[k][i]
    return ma

In [6]:
for l in range(iter_no):
    print("---------", l, "------------")
    for i in range(n):
        for j in range(n):
            M_ab_new[i][j] = w[i][j] - calc_max(M_ba, i, j, n)
            M_ba_new[i][j] = w[j][i] - calc_max(M_ab, i, j, n)

    P = np.argmax(M_ba_new, axis=1)

    M_ab = M_ab_new
    M_ba = M_ba_new
    
    print(M_ab_new)
    print(M_ba_new)

    print(P)


--------- 0 ------------
[[ 12. -14. -12.]
 [-11.  -9.   9.]
 [-11.   9.  -9.]]
[[ 11. -11. -13.]
 [-12.  -7.   7.]
 [-12.  11. -11.]]
[0 2 1]
--------- 1 ------------
[[ 10. -25. -23.]
 [-24. -22.  18.]
 [-33.   7. -31.]]
[[  9. -23. -25.]
 [-25. -20.  18.]
 [-32.   7. -31.]]
[0 2 1]
--------- 2 ------------
[[ 23. -38. -36.]
 [-20. -18.  16.]
 [-29.  27. -27.]]
[[ 22. -36. -38.]
 [-23. -18.  14.]
 [-30.  29. -29.]]
[0 2 1]
--------- 3 ------------
[[ 21. -34. -32.]
 [-42. -40.  32.]
 [-45.  25. -43.]]
[[ 18. -34. -36.]
 [-43. -38.  30.]
 [-46.  25. -45.]]
[0 2 1]
--------- 4 ------------
[[ 41. -56. -54.]
 [-38. -36.  34.]
 [-47.  41. -45.]]
[[ 40. -54. -56.]
 [-41. -36.  32.]
 [-48.  41. -47.]]
[0 2 1]
--------- 5 ------------
[[ 39. -52. -50.]
 [-54. -52.  50.]
 [-63.  43. -61.]]
[[ 36. -52. -54.]
 [-57. -52.  48.]
 [-64.  43. -63.]]
[0 2 1]
--------- 6 ------------
[[ 55. -68. -66.]
 [-56. -54.  52.]
 [-65.  59. -63.]]
[[ 52. -68. -70.]
 [-59. -54.  50.]
 [-66.  59. -65.]]
[0 2 1]